cloudflare-project: "aptispace-ia"

project:
  type: book
  output-dir: _site
  pre-render: bash _extensions/aptitek/download-fonts/download_fonts.sh
  post-render: 
    - find cours -type d -name "*_files" -exec rm -rf {} +
    - find cours -type d -name "*_cache" -exec rm -rf {} +
  resources:
    - "lab/**"
    - "assets/**"

bibliography: bibliography.bib

filters:
  - aptitek/graph
  - filetree
  - card
  - timeline
  - embed
  - aptitek/zoom

book:
  title: "Intelligence Artificielle"
  author: "Aptitek"
  search: false
  site-url: "https://ia.apti.space"
  
  sidebar:
    logo: "assets/logo.svg"
    logo-href: "/"
    logo-alt: "Aptitek"
    style: "docked"
    search: false
  
  chapters:
    - index.qmd
    - part: "🎯 Module"
      chapters:
        - meta/module.qmd
        - meta/syllabus.qmd
        - meta/planning.qmd
    - part: "🔭 Fondations & Vision"
      chapters:
        - cours/1_intro/index.qmd
        - cours/2_vision/index.qmd
    - part: "🎭 Génération & Orchestration"
      chapters:
        - cours/3_genai/index.qmd
        - cours/4_agents/index.qmd
    - part: "🔮 Éthique & Futur"
      chapters:
        - cours/5_ethique/index.qmd
    - part: "🛠️ Lab & Projets"
      chapters:
        - lab/projet.qmd
    - part: "📚 Annexes"
      chapters:
        - aide-memoire.qmd
        - glossaire.qmd
        - references.qmd

format:
  html:
    theme:
      - solar
      - .theme/theme.scss
    mainfont: "Recursive"
    monofont: "Recursive"
    highlight-style: solarized
    toc: true
    code-copy: true
    code-tools:
      source: true
      toggle: false
      caption: "Voir le code source"
    mermaid:
      theme: neutral
    html-math-method: katex
    number-sections: true
    header-includes: |
      <meta name="robots" content="noindex, nofollow">
    include-after-body: assets/fix_links.html
    css: .theme/book_custom.css

# Le format Typst est temporairement désactivé car non supporté nativement par les projets "book" dans cette version de Quarto
#  typst:
#    toc: true
#    number-sections: true
#    font-paths:
#      - "fonts"
#    mainfont: "Recursive Sans Linear"
#    papersize: a4